name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Additional setup
      run: |
        sudo apt-get update
        sudo apt-get install -y libhidapi
        go install golang.org/x/tools/cmd/stringer

    - name: Generate
      run: go generate -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
